export const SECOND_TO_MS = 1000;
export const CALC_PER_SECOND = 10;
export const PRODUCTION_INTERVAL = SECOND_TO_MS / CALC_PER_SECOND;

export const QUARK_PROD = 0.001 / CALC_PER_SECOND;
export const QUARK_FUNDAMENTAL_INTERACTIONS_MULTIPLIER = 10;

export const ELECTRON_BASE_PROD = 0.005 / CALC_PER_SECOND;

export const PROTON_BASE_PROD = 0.001 / CALC_PER_SECOND;

export const NEUTRON_BASE_PROD = 0.001 / CALC_PER_SECOND;
